# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d8249705a0d434c5c9499dc0f697310d448ef8a1753531688f338e7f3a5a2953f16ae802a4ad77ac74ad6585d845d5bd8d03a2c0448c729bcf763fc5841baa

test:
  secret_key_base: 2fe360436ea2390dd4b315402bed10975c9d03394c58be8ca9d6a0584db0955f0ceefa7684b79e2bbae7f36400ad75fb11df413841b9c8436a26920921af85ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
